/// <reference types="cypress" />
describe('test signup function', () => {
  beforeEach(() => {
    cy.visit(' http://localhost:4200/register')  
  })
  it('Check if text is present', () => {
    cy.get('h1').contains('SignUp Form')
    cy.get('.mat-form-field.ng-tns-c67-1 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Email')
    cy.get('.mat-form-field.ng-tns-c67-2 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Password *')
    cy.get('.mat-form-field.ng-tns-c67-3 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','name *')
  })
  it('Fill the deatails to create an account', () => {
    cy.get('#mat-input-0').type('nagarjunareddyboya@gmail.com')
    cy.get('#mat-input-1').type('Nagarjuna@123')
    cy.get('#mat-input-2').type('Nagarjuna Reddy Boya')
    cy.get('.mat-button-wrapper').click()
    cy.get('h1').should('have.text','Login Form')
    cy.get('.mat-form-field.ng-tns-c67-4 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Email')
    cy.get('.mat-form-field.ng-tns-c67-5 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Password *')
    cy.get('#mat-input-3').type('nagarjunareddyboya@gmail.com')
    cy.get('#mat-input-4').type('Nagarjuna@123')
    cy.get('.mat-button-wrapper').click()
    cy.get('.group2 > .mat-raised-button').click()
    cy.get('.mat-menu-trigger').click()
    cy.get('.mat-menu-content > :nth-child(2) > span').click()
    cy.get('h1').should('have.text', 'Create your Event here.')
    cy.get('#mat-hint-0').should('have.text','Enter the event Name')
    cy.get('#mat-hint-1').should('have.text','Provide secondary details')
    cy.get('#mat-hint-2').should('have.text','Please provide description')
    cy.get('#mat-hint-3').should('have.text','Provide the event ticket price')
    cy.get('#mat-hint-4').should('have.text','Please provide address of the Event')
    cy.get('#mat-hint-5').should('have.text','Enter the name of the building where the event is conducted')
    cy.get('.mat-form-field.ng-tns-c67-14 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Event Name *')
    cy.get('.mat-form-field.ng-tns-c67-15 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Event Info *')
    cy.get('.mat-form-field.ng-tns-c67-16 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Description *')
    cy.get('.mat-form-field.ng-tns-c67-17 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Sample Description *')
    cy.get('.mat-form-field.ng-tns-c67-19 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Category *')
    cy.wait(2000)
    cy.get('#mat-input-11').type('Mass on the Grass')
    cy.wait(2000)
    cy.get('#mat-input-12').type('Weekly')
    cy.wait(2000)
    cy.get('#mat-input-13').type('Celebrate Mass on Ash Wednesday in Campus')
    cy.wait(2000)
    cy.get('#mat-input-14').type('Celebrate Mass on Ash Wednesday in Campus')
    cy.wait(2000)
    cy.get('#mat-input-15').clear().type('4')
    cy.wait(2000)
    cy.get('#mat-input-16').type('In-person')
    cy.wait(2000)
    cy.get('#mat-input-17').type('Plaza of the Americas')
    cy.wait(2000)
    cy.get('#mat-input-18').type('2022-05-03T15:00')
    cy.wait(2000)
    cy.get('.event_form_container__flex > .mat-focus-indicator > .mat-button-wrapper').click()
    cy.wait(1000)
    cy.get('h1').should('have.text','Login Form')
    
    cy.get('.mat-form-field.ng-tns-c67-22 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Email')
    cy.get('.mat-form-field.ng-tns-c67-23 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Password *')
    cy.get('#mat-input-19').type('nagarjunareddyboya@gmail.com')
    cy.get('#mat-input-20').type('Nagarjuna@123')
    cy.wait(2000)
    cy.get('.login-container__form > .mat-focus-indicator > .mat-button-wrapper').click()
    cy.wait(4000)
    cy.contains('Mass on the Grass')
      cy.contains('Weekly')
      cy.contains('4')
      cy.contains('Celebrate Mass on Ash Wednesday in Campus')
      cy.contains('Plaza of the Americas')
      cy.get(':nth-child(1) > .mat-card').click()
      cy.contains('Mass on the Grass')
      cy.contains('Weekly')
      cy.contains('In-person')
      cy.contains('4')
      cy.contains('Celebrate Mass on Ash Wednesday in Campus')
      cy.contains('Plaza of the Americas')

      cy.get('.mat-menu-trigger').click()
    cy.get('.mat-menu-content > :nth-child(2) > span').click()
    cy.get('h1').should('have.text', 'Create your Event here.')
    cy.get('#mat-hint-6').should('have.text','Enter the event Name')
    cy.get('#mat-hint-7').should('have.text','Provide secondary details')
    cy.get('#mat-hint-8').should('have.text','Please provide description')
    cy.get('#mat-hint-9').should('have.text','Provide the event ticket price')
    cy.get('#mat-hint-10').should('have.text','Please provide address of the Event')
    cy.get('#mat-hint-11').should('have.text','Enter the name of the building where the event is conducted')
    cy.get('.mat-form-field.ng-tns-c67-32 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Event Name *')
    cy.get('.mat-form-field.ng-tns-c67-33 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Event Info *')
    cy.get('.mat-form-field.ng-tns-c67-34 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Description *')
    cy.get('.mat-form-field.ng-tns-c67-35 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Sample Description *')
    cy.get('.mat-form-field.ng-tns-c67-37 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Category *')
    cy.wait(2000)
    cy.get('#mat-input-27').type('Shaving Cream Showdown')
    cy.wait(2000)
    cy.get('#mat-input-28').type('Yearly')
    cy.wait(2000)
    cy.get('#mat-input-29').type('The purpose of this event is to build housing community')
    cy.wait(2000)
    cy.get('#mat-input-30').type('The purpose of this event is to build housing community')
    cy.wait(2000)
    cy.get('#mat-input-31').clear().type('10')
    cy.wait(2000)
    cy.get('#mat-input-32').type('In-person')
    cy.wait(2000)
    cy.get('#mat-input-33').type('Weaver Hall')
    cy.wait(2000)
    cy.get('#mat-input-34').type('2022-10-03T16:00')
    cy.wait(2000)
    cy.get('.event_form_container__flex > .mat-focus-indicator > .mat-button-wrapper').click()
    cy.get('h1').should('have.text','Login Form')
    cy.get('.mat-form-field.ng-tns-c67-40 > .mat-form-field-wrapper > .mat-form-field-flex').should('have.text','Email')
    cy.get('.mat-form-field.ng-tns-c67-41 > .mat-form-field-wrapper > .mat-form-field-flex').should('have.text','Password *')
    cy.get('#mat-input-35').type('nagarjunareddyboya@gmail.com')
    cy.get('#mat-input-36').type('Nagarjuna@123')
    cy.wait(2000)
    cy.get('.login-container__form > .mat-focus-indicator > .mat-button-wrapper').click()
    cy.wait(2000)
    cy.contains('Shaving Cream Showdown')
    cy.contains('Yearly')
    cy.contains('10')
    cy.contains('The purpose of this event is to build housing community')
    cy.contains('Weaver Hall')
    cy.get(':nth-child(2) > .mat-card').click()
    cy.contains('Shaving Cream Showdown')
    cy.contains('Yearly')
    cy.contains('In-person')
    cy.contains('10')
    cy.contains('The purpose of this event is to build housing community')
    cy.contains('Weaver Hall')
    cy.get('.mat-menu-trigger').click()
    cy.get(':nth-child(3) > span').click()
    
  })


  
describe('test create function', () => {
    beforeEach(() => {
      cy.visit(' http://localhost:4200/create')
      cy.wait(4000)
    })
    it('Check if text is present', () => {
      cy.contains('Create your Event here.')

      cy.get('h1').should('have.text', 'Create your Event here.')
      cy.get('#mat-hint-0').should('have.text','Enter the event Name')
      cy.get('#mat-hint-1').should('have.text','Provide secondary details')
      cy.get('#mat-hint-2').should('have.text','Please provide description')
      cy.get('#mat-hint-3').should('have.text','Provide the event ticket price')
      cy.get('#mat-hint-4').should('have.text','Please provide address of the Event')
      cy.get('#mat-hint-5').should('have.text','Enter the name of the building where the event is conducted')
      cy.get('.mat-form-field.ng-tns-c86-0 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Event Name *')
      cy.get('.mat-form-field.ng-tns-c86-1 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Event Info *')
      cy.get('.mat-form-field.ng-tns-c86-2 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Description *')
      cy.get('.mat-form-field.ng-tns-c86-3 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Sample Description *')
      cy.get('.mat-form-field.ng-tns-c86-5 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Category *')

    })

    it('Fill the third event details, post and check if it is getting posted', () => {
    cy.wait(2000)
  cy.get('#mat-input-0').type('Tide Slide')
  cy.wait(2000)
  cy.get('#mat-input-1').type('Monthly')
  cy.wait(2000)
  cy.get('#mat-input-2').type('This event is to raise money for Dance Marathon')
  cy.wait(2000)
  cy.get('#mat-input-3').type('This event is to raise money for Dance Marathon')
  cy.wait(2000)
  cy.get('#mat-input-4').type('0')
  cy.wait(2000)
  cy.get('#mat-input-5').type('In-person')
  cy.wait(2000)
  cy.get('#mat-input-6').type('Fraternity House')
  cy.wait(2000)
  cy.get('#mat-input-7').type('2022-04-16T16:30')
  cy.wait(2000)
  cy.get('.mat-button-wrapper').click()
  cy.wait(1000)
  cy.get('h1').should('have.text','Login Form')
    cy.get('.mat-form-field.ng-tns-c86-8 > .mat-form-field-wrapper > .mat-form-field-flex').should('have.text','Email')
    cy.get('.mat-form-field.ng-tns-c86-9 > .mat-form-field-wrapper > .mat-form-field-flex').should('have.text','Password *')
    cy.get('#mat-input-8').type('nagarjunareddyboya@gmail.com')
    cy.get('#mat-input-9').type('nagarjuna')
  cy.wait(2000)
  })
})

describe('test event display function', () => {
    beforeEach(() => {
      cy.visit(' http://localhost:4200/events')
      cy.wait(4000)
    })

    it('check if it is getting posted', () => {
  cy.wait(1000)
  cy.contains('Tide Slide')
  cy.contains('Monthly')
  cy.contains('0')
  cy.contains('This event is to raise money for Dance Marathon')
  cy.contains('Fraternity House')
  cy.get(':nth-child(3) > .mat-card').click()
  cy.wait(1000)
  cy.contains('Tide Slide')
  cy.contains('Monthly')
  cy.contains('In-person')
  cy.contains('0')
  cy.contains('This event is to raise money for Dance Marathon')
  cy.contains('Fraternity House')

  })
})

describe('test create function', () => {
  beforeEach(() => {
    cy.visit(' http://localhost:4200/create')
    cy.wait(4000)
  })
 
  it('Check if text is present', () => {
      cy.contains('Create your Event here.')

      cy.get('h1').should('have.text', 'Create your Event here.')
      cy.get('#mat-hint-0').should('have.text','Enter the event Name')
      cy.get('#mat-hint-1').should('have.text','Provide secondary details')
      cy.get('#mat-hint-2').should('have.text','Please provide description')
      cy.get('#mat-hint-3').should('have.text','Provide the event ticket price')
      cy.get('#mat-hint-4').should('have.text','Please provide address of the Event')
      cy.get('#mat-hint-5').should('have.text','Enter the name of the building where the event is conducted')
      cy.get('.mat-form-field.ng-tns-c86-0 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Event Name *')
      cy.get('.mat-form-field.ng-tns-c86-1 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Event Info *')
      cy.get('.mat-form-field.ng-tns-c86-2 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Description *')
      cy.get('.mat-form-field.ng-tns-c86-3 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Sample Description *')
      cy.get('.mat-form-field.ng-tns-c86-5 > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').should('have.text','Category *')

     
  })


  it('Fill the fourth event details, post and check if it is getting posted', () => {
  cy.wait(2000)
  cy.get('#mat-input-0').type('Southeast Sisterhood Conference')
  cy.wait(2000)
  cy.get('#mat-input-1').type('Yearly')
  cy.wait(2000)
  cy.get('#mat-input-2').type('A celebration for our Southeast regional chapters.')
  cy.wait(2000)
  cy.get('#mat-input-3').type('A celebration for our Southeast regional chapters.')
  cy.wait(2000)
  cy.get('#mat-input-4').type('15')
  cy.wait(2000)
  cy.get('#mat-input-5').type('In-person')
  cy.wait(2000)
  cy.get('#mat-input-6').type('Reitz Union')
  cy.wait(2000)
  cy.get('#mat-input-7').type('2022-05-03T15:00')
  cy.wait(2000)
  cy.get('.mat-button-wrapper').click()
  cy.wait(1000)
  cy.get('h1').should('have.text','Login Form')
    cy.get('.mat-form-field.ng-tns-c86-8 > .mat-form-field-wrapper > .mat-form-field-flex').should('have.text','Email')
    cy.get('.mat-form-field.ng-tns-c86-9 > .mat-form-field-wrapper > .mat-form-field-flex').should('have.text','Password *')
    cy.get('#mat-input-8').type('nagarjunareddyboya@gmail.com')
    cy.get('#mat-input-9').type('nagarjuna')
  cy.wait(2000)
  })
})

describe('test event display function', () => {
  beforeEach(() => {
    cy.visit(' http://localhost:4200/events')
    cy.wait(4000)
  })
  it('check if it is getting posted', () => {
  cy.wait(2000)
  cy.contains('Southeast Sisterhood Conference')
  cy.contains('Yearly')
  cy.contains('15')
  cy.contains('A celebration for our Southeast regional chapters.')
  cy.contains('Reitz Union')
  cy.get(':nth-child(4) > .mat-card').click()
  cy.contains('Southeast Sisterhood Conference')
  cy.contains('Yearly')
  cy.contains('In-person')
  cy.contains('15')
  cy.contains('A celebration for our Southeast regional chapters.')
  cy.contains('Reitz Union')

  })
 
})